### ISSUE TITLE
support init containers

### ISSUE THREAD

**Issue by AmirAliSobhGol** [rycus86/podlike#2]
in k8s there is a concept of init containers which can be used to setup config, run scripts etc. before starting a pod for example a real use case is: using the init container to register the gitlab-runner with the hosted gitlab before starting the gitlab-runner container to fetch jobs.
here is a link for further description:
https://kubernetes.io/docs/concepts/workloads/pods/init-containers/

**Comment by rycus86** [comment]
Thanks for the suggestion!
It makes a lot of sense. I did something similar with a specialized container and `depends_on`, but replicating this k8s feature would make it easier and more generic.

I'll have a look at it when I get some time!

**Comment by rycus86** [comment]
I've just added initial support for this in https://github.com/rycus86/podlike/commit/3968f0db2c1d236261342fac22ff87d45c45797a

It's the main app only at the moment, so template support is missing. If you want to try it, add a label to the service like:

```yaml
services:

  sample:
    image: rycus86/podlike:latest  # for now
    labels:
      pod.init.components: |
        - image: init/one
          command: something exciting
        - image: init/two
          command: another one
      pod.component.test: |
        image: actual/component
        command: run
```

Let me know what do you think about it! Thanks!
