### ISSUE TITLE
can't join IPC of container error

### ISSUE THREAD

**Issue by mxrlkn** [rycus86/podlike#5]
I'm just trying out podlike with 2 managers and a simple example and It stops with this log:

```
system_pod.0.r99lwm4laykp@test-01    | Using API version: 1.40
system_pod.0.r99lwm4laykp@test-01    | Starting component: app
system_pod.0.r99lwm4laykp@test-01    | Exited: app Error: Failed to start app: Error response from daemon: can't join IPC of container 3a556027d5a3aa858a5db8e10a216d5d5354b538085dc489bb7b726061b17711: non-shareable IPC (hint: use IpcMode:shareable for the donor container)
system_pod.0.r99lwm4laykp@test-01    | Stopping container: app
system_pod.0.r99lwm4laykp@test-01    | Failed to stop the container: Error response from daemon: No such container: 4a933b2efcc750fa630cc491a56d241377fe1e60f27002067c1dbb54c661f780
system_pod.0.r99lwm4laykp@test-01    | Failed to remove the container: Error: No such container: 4a933b2efcc750fa630cc491a56d241377fe1e60f27002067c1dbb54c661f78
```

docker-compose.yml:

```
version: "3.7"

services:
  pod:
    image: rycus86/podlike
    command: -logs
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "80:80"
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
    labels:
      pod.component.app: |
        image: containous/whoami
```

docker version: 19.03.1

Maybe I'm missing something?

**Comment by rycus86** [comment]
Huh, I haven't seen that before. It could be something new with how Docker handles IPC, last time I checked this was on something like 18.03 or similar.
Maybe try `ipc: shareable` as the error message suggests? https://docs.docker.com/engine/reference/run/#ipc-settings---ipc

**Comment by mtm-sig** [comment]
Just tried adding ipc: shareable to my docker-compose.yml:

```
version: "3.7"

services:
  pod:
    image: rycus86/podlike
    command: -logs
    ipc: shareable
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "80:80"
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
    labels:
      pod.component.app: |
        image: containous/whoami
```

and when I run `docker stack deploy` it logs:

`Ignoring unsupported options: ipc`

So I guess this is one of those options that doesn't work in swarm mode. I couldn't find a whole lot of information about it.

**Comment by mxrlkn** [comment]
Just tried adding ipc: shareable to my docker-compose.yml:

```
version: "3.7"

services:
  pod:
    image: rycus86/podlike
    command: -logs
    ipc: shareable
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "80:80"
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
    labels:
      pod.component.app: |
        image: containous/whoami
```

and when I run `docker stack deploy` it logs:

`Ignoring unsupported options: ipc`

So I guess this is one of those options that doesn't work in swarm mode. I couldn't find a whole lot of information about it.
